apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  configuration: |
      terraform {
        backend "kubernetes" {
          secret_suffix     = "providerconfig-aws-eu-west-1"
          namespace         = "upbound-system"
          in_cluster_config = true
        }
      }
  logConfig:
    backupLogFilesCount: 1
    enableLogging: True
